---
title: "Lab 00 - Computer Setup"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format: pdf
---

**Note:** Positron currently has a bug with quarto on Windows. 
If `format: pdf` does not work, try `format: typst` and I *think* that should fix it. 
If it does not, let me know and I will help you troubleshoot.

# Assignment

1. Say you have a Saturday afternoon free, no responsibilities, and money in checkings. 
   What would you do with your afternoon?

**Answer:**




2. Insert a code chunk with the content being `1 + 1`. 
   If you don't know what a code chunk is, refer to [these notes](https://evalf21.classes.andrewheiss.com/resource/rmarkdown/). 
   Your knitted document should have the results of the code displayed below, i.e. `# 2`.

**Answer:**





3. Below, I've taken the mean of ages of students in a surveyed classroom. 
   I've stored that in a variable called `mean_ages`. 
   In the Answer area, please write a sentence telling me the mean ages using the [inline R chunk syntax](https://evalf21.classes.andrewheiss.com/resource/rmarkdown/#inline-chunks). 

```{r}
ages <- c(20, 18, 21, 19, 20, 17, 22, 19, 18, 19)
mean_ages <- mean(ages)
```

**Answer:**

The average age of the students is 


