## Classical Decomposition

Let's now try to do a decomposition of the monthly electrical sales

```{r}
library(lubridate)
library(fixest)
electrical <- read.csv("data/electrical_manufacturing_eu.csv")
electrical$day <- ymd(electrical$day)
```

Step 1: Estimate trend using a $2 \times 12 MA$, $\hat{T}_t$

```{r}
# 12-MA
electrical$q_12_ma <- slider::slide_dbl(
  electrical$q_manufactured, mean,
  .before = 5, .after = 6, .complete = TRUE
)
# 2 x 12-MA
electrical$q_trend <- slider::slide_dbl(
  electrical$q_12_ma, mean,
  .before = 1, .after = 0, .complete = TRUE
)
```

Step 2: Take the difference between $y_t$ and $\hat{T}_t$

```{r}
electrical$q_detrended <- electrical$q_manufactured <- electrical$q_trend
```

Step 3: Estimate monthly seasonality, $\hat{S}_t$
```{r}
est_monthly <- feols(
  q_detrended ~ i(month(day)), data = electrical
)
electrical$q_seasonality <- predict(est_monthly, newdata = electrical)
```

Step 4: Take difference between $y_t$ and $\hat{T}_t + \hat{S}_t$ to get residuals

```{r}
electrical$q_trend_and_season <- electrical$q_trend + electrical$q_seasonality
electrical$q_resid <- electrical$q_manufactured - electrical$q_trend_and_season
```

Last, we will plot each:

```{r}
plot(electrical$day, electrical$q_manufactured)
plot(electrical$day, electrical$q_trend, col = "red")
plot(electrical$day, electrical$q_trend_and_season, col = "blue")
plot(electrical$day, electrical$q_resid, col = "orange")
```

